# Generated by Django 5.1.7 on 2025-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=300)),
                ('rokPremiery', models.IntegerField(blank=True, null=True)),
                ('obrazekUrl', models.CharField(max_length=300)),
                ('zanr', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('obsah', models.TextField(blank=True, default='')),
                ('pocetHvezd', models.IntegerField()),
                ('datumPridani', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=300)),
                ('povolani', models.CharField(max_length=300)),
                ('obrazekUrl', models.CharField(max_length=300)),
                ('filmy', models.ManyToManyField(related_name='associated_people', to='main.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='herci',
            field=models.ManyToManyField(related_name='acted_films', to='main.osoba'),
        ),
        migrations.AddField(
            model_name='film',
            name='reziseri',
            field=models.ManyToManyField(related_name='directed_films', to='main.osoba'),
        ),
        migrations.AddField(
            model_name='film',
            name='recenze',
            field=models.ManyToManyField(related_name='film_reviews', to='main.recenze'),
        ),
    ]
