# Generated by Django 5.1.7 on 2025-06-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='filmy',
        ),
        migrations.AlterField(
            model_name='film',
            name='herci',
            field=models.ManyToManyField(blank=True, related_name='acted_films', to='main.osoba'),
        ),
        migrations.AlterField(
            model_name='film',
            name='recenze',
            field=models.ManyToManyField(blank=True, related_name='film_reviews', to='main.recenze'),
        ),
        migrations.AlterField(
            model_name='film',
            name='reziseri',
            field=models.ManyToManyField(blank=True, related_name='directed_films', to='main.osoba'),
        ),
    ]
